"""Alembic environment: async engine, URL sourced from `Settings`.

Deliberately does NOT read `sqlalchemy.url` out of `alembic.ini` -- the
connection URL comes from `jobact.shared.infrastructure.config.get_settings()`
(the same `Settings` the application itself uses), so there is exactly one
place that assembles a Postgres URL for this codebase.
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from jobact.shared.infrastructure.config import get_settings

# this is the Alembic Config object, which provides access to values
# within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# No ORM/declarative models are autogenerated against yet -- the baseline
# migration (and, for now, every migration in this milestone) is
# hand-written, not autogenerated from `target_metadata`.
target_metadata = None

# Override whatever `sqlalchemy.url` alembic.ini has with the real URL.
config.set_main_option("sqlalchemy.url", get_settings().database_url)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine,
    though an Engine is acceptable here as well. By skipping the Engine
    creation we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Create an Engine and associate a connection with the context."""
    # connect_args ssl=False: see Settings.postgres_ssl docstring -- asyncpg's
    # default SSL negotiation hangs into a connection reset against a
    # non-SSL Postgres on Windows' ProactorEventLoop.
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args={"ssl": get_settings().postgres_ssl},
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
